### ISSUE TITLE
How do you use an agent wisely with multiple users?

### ISSUE THREAD

**Issue by sudddy** [openwallet-foundation/agent-framework-javascript#1689]
Consider I have an issuer agent (Nodejs) using Aries JavaScript framework. So in my platform, if there are multiple users 

1. Should I be using the same agent initialized with the a default wallet credentials for all the users. I understand it's a personal preference. But if that's the case,  all of the credentials issued will be available for all users. Is this something to be handled in agent or the application on top of it should handle it?

I have looked into  tenant agent. But it is limited to max of 100 sessions which might be a issue if there are more users.

Any comments on this would be appreciated 🙏🙏

**Comment by TimoGlastra** [comment]
The tenants module is definitely what you should use for this.

You can configure the limit of 100 sessions, and either set it higher or to inifinity if you don't want to limit it

**Comment by TimoGlastra** [comment]
See https://github.com/openwallet-foundation/agent-framework-javascript/blob/main/packages/tenants/src/TenantsModuleConfig.ts#L14

**Comment by sudddy** [comment]
Thanks, @TimoGlastra 🙏
