### ISSUE TITLE
[QUESTION] Creating a proof with multiple credentials with same schema/credential definition

### ISSUE THREAD

**Issue by icc-romeu** [openwallet-foundation/agent-framework-javascript#1695]
Hi,

We are trying to request multiple credentials of the same credential definition/schema with Aries/Indy. Say we try to get a university degree. If a user has more than one credential, because s/he has multiple degrees, how can that be done? Is there a way of creating a proof request for it?

**Comment by TimoGlastra** [comment]
Here also a relevant thread in PEX: https://github.com/decentralized-identity/presentation-exchange/issues/406

We're working on supporting PEX with AnonCreds represented as W3C credential. Maybe once that has landed you can use some of the workaround/hacks as listed in the above issue

**Comment by pabloromeu** [comment]
Thanks @TimoGlastra ! 

BTW Awesome work! 👍 much appreciated!

**Comment by icc-romeu** [comment]
Thanks @TimoGlastra !

BTW Awesome work! 👍 much appreciated!
