### ISSUE TITLE
Unable to Determine Tenant ID for Inbound Message in Connectionless Credential Issuance

### ISSUE THREAD

**Issue by Sshovon** [openwallet-foundation/agent-framework-javascript#1701]
I use a multi-tenancy configuration with the Aries Framework's tenants module, version 0.4.2, for both the issuer and holder agent. On the issuer side, I create a credential offer and an oob invitation with the handshake set to false, including the credential offer message in the invitation. On the holder side, I initiate the connection acceptance using `oob.receiveInvitationFromUrl` and subsequently accept the credential offer through `credentials.acceptOffer`. The holder agent receives the credential request upon invoking the `receiveInvitationFromUrl` function and emits a `request-sent` event after the execution of `credentials.acceptOffer`. Notably, the issuer does not emit any events related to the credential state change upon receiving the request from the holder, and an error is observed in the issuer's logger trace.
```
ERROR: Error processing inbound message: Couldn't determine tenant id for inbound message. Unable to create context {
  "name": "AriesFrameworkError",
  "message": "Couldn't determine tenant id for inbound message. Unable to create context",
  "stack": "AriesFrameworkError: Couldn't determine tenant id for inbound message. Unable to create context\n    at TenantAgentContextProvider.getContextForInboundMessage (/home/agents/node_modules/@aries-framework/tenants/src/context/TenantAgentContextProvider.ts:96:13)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async MessageReceiver.receiveMessage (/home/agents/node_modules/@aries-framework/core/src/agent/MessageReceiver.ts:90:26)\n    at async /home/agents/node_modules/@aries-framework/node/src/transport/HttpInboundTransport.ts:51:9"
}
```

**Comment by TimoGlastra** [comment]
There should be a log created when the out of band invitation is created with the following structure (ids and keys replaced): 

```
Received routing key created event for tenant ${contextCorrelationId}, registering recipient key ${recipientKey.fingerprint} in base wallet
```

Could you check if this is logged for key `z6MkmVciTJHbWSofUsYAqu9MSB7oQ3xq9NPWVn1dTfGfFru6`?

**Comment by TimoGlastra** [comment]
And could you also check if a `RoutingCreatedEvent` is emitted (`RoutingEventTypes.RoutingCreatedEvent`) at the time you create the invitation?

https://github.com/openwallet-foundation/agent-framework-javascript/blob/main/packages/core/src/modules/routing/services/RoutingService.ts#L44-L50

It should emit this, and that's what the tenants module hooks into for registering the mapping of key -> tenantId.

**Comment by TimoGlastra** [comment]
And finally could you check if this is logged after startup of the agent:

```
Listening for routing key created events in tenant agent context provider
```

**Comment by Sshovon** [comment]
It's resolved. Thanks.

**Comment by TimoGlastra** [comment]
What was the solution?

**Comment by Sshovon** [comment]
The issue was occurring possibly due to conflicting packages. I have cleared the yarn cache, removed the node_modules, and reinstalled the dependencies. It worked for the same code.
